HW #1
Nikitosh/SPbAU-Software-Design-Course-5th-Term pull request #1
Opened 2016-10-09 19:04 UTC by Nikitosh

2016-10-17 22:39 UTC, yurii-litvinov requested changes
Ещё нужно краткое архитектурное описание. Просто перечисление команд --- это слишком кратко :) А вообще, очень годно, но мелкие замечания по коду, пожалуйста, поправьте.

2016-10-17 22:39 UTC, yurii-litvinov commented on src/main/java/com/nikitosh/spbau/Environment.java
> +
Комментарии от комментируемой сущности пустой строкой обычно не отделяются.

2016-10-17 22:39 UTC, yurii-litvinov commented on src/main/java/com/nikitosh/spbau/Environment.java
> +     * @param variable name of variable.
В комментарии ещё нужно общее описание метода, оно генерится в список методов класса, комментарии с тэгами --- в детальную информацию. Ниже по всей программе тоже, хоть немного, но про каждый метод лучше писать. Работа с плохо документированным кодом вызывает боль.

2016-10-17 22:39 UTC, yurii-litvinov commented on src/main/java/com/nikitosh/spbau/Environment.java
> +     * @return         value of given variable.
Зачем столько пробелов? :)

2016-10-17 22:39 UTC, yurii-litvinov commented on src/main/java/com/nikitosh/spbau/LexerImpl.java
> +        public List<Lexeme> substitute(List<Lexeme> lexemes, Environment environment) {
Тут с отступом что-то не то.

2016-10-17 22:39 UTC, yurii-litvinov commented on src/main/java/com/nikitosh/spbau/Shell.java
> +                if (commandLine.equals(EXIT)) {
При таком подходе не будет работать
```
x=exit
$x
```
но это так, можно не править.

2016-10-17 22:54 UTC, Nikitosh commented on src/main/java/com/nikitosh/spbau/Environment.java
> +
Не уверен, что с классами так же (по крайней, мере в официальном JavaDoc-е JDK, например,  комментарий перед классом отделяется пустой строкой, см. http://www.docjar.net/html/api/java/util/AbstractMap.java.html)

2016-10-17 22:56 UTC, Nikitosh commented on src/main/java/com/nikitosh/spbau/Environment.java
> +     * @return         value of given variable.
Мне кажется, что удобнее и более читаемо, когда описание всех параметров, а так же возвращаемое значение выровнены по левому краю.

2016-10-17 22:58 UTC, Nikitosh commented on src/main/java/com/nikitosh/spbau/Shell.java
> +                if (commandLine.equals(EXIT)) {
Да, но даже в задании было написано, что "exit можно обрабатывать отдельно".

2016-10-17 23:01 UTC, yurii-litvinov commented on src/main/java/com/nikitosh/spbau/Environment.java
> +
Ок, убедили. Хотя стайлгайд от Google рекомендует не отделять (https://google.github.io/styleguide/javaguide.html#s4.6-whitespace и пример кода https://developers.google.com/youtube/v3/code_samples/java), пусть будет можно и так и так.

2016-10-17 23:04 UTC, yurii-litvinov commented on src/main/java/com/nikitosh/spbau/Environment.java
> +     * @return         value of given variable.
При рефакторинге длина имени какой-нибудь переменной может поменяться, что приведёт к каскаду выравниваний и негативно скажется на диффах.

2016-10-17 23:28 UTC, Nikitosh commented
@yurii-litvinov 
Добавил комментарии к методам, убрал лишние пробелы, добавил описание архитектуры.

2016-10-18 08:28 UTC, yurii-litvinov approved these changes

2016-10-18 08:28 UTC, merged